### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException

### ISSUE THREAD

**Issue by valleballe** [mindslab-ai/cotatron#2]
I am having issues with the cotatron training; in particular with the pytorch-lightning package. I've found that the code only runs with pytorch-lightning<=0.7.3, yet it is unable to identify my GPU:

```Traceback (most recent call last):
  File "cotatron_trainer.py", line 72, in <module>
    main(args)
  File "cotatron_trainer.py", line 36, in main
    trainer = Trainer(
  File "/home/valleballe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 389, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/home/valleballe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 629, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/home/valleballe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 596, in sanitize_gpu_ids
    raise MisconfigurationException(f"""
pytorch_lightning.utilities.exceptions.MisconfigurationException:
                You requested GPUs: [1]
                But your machine only has: []
```

I have the same result when setting the " -g" argument to "0".

My environment packages:
```Package                Version
---------------------- -------------
absl-py                0.9.0
attrs                  19.3.0
audioread              2.1.8
Automat                0.8.0
blinker                1.4
cachetools             4.1.0
certifi                2019.11.28
cffi                   1.14.0
chardet                3.0.4
Click                  7.0
cloud-init             20.1
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
cycler                 0.10.0
dbus-python            1.2.16
decorator              4.4.2
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
future                 0.18.2
google-auth            1.16.0
google-auth-oauthlib   0.4.1
grpcio                 1.29.0
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
imageio                2.8.0
importlib-metadata     1.5.0
incremental            16.10.1
inflect                4.1.0
Jinja2                 2.10.1
joblib                 0.15.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
kiwisolver             1.2.0
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
librosa                0.7.2
llvmlite               0.32.1
Markdown               3.2.2
MarkupSafe             1.1.0
matplotlib             3.2.1
more-itertools         4.2.0
netifaces              0.10.4
numba                  0.49.1
numpy                  1.18.5
oauthlib               3.1.0
omegaconf              2.0.0
pandas                 1.0.4
Pillow                 7.1.2
pip                    20.0.2
protobuf               3.12.2
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycparser              2.20
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyOpenSSL              19.0.0
pyparsing              2.4.7
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0
python-dateutil        2.8.1
python-debian          0.1.36ubuntu1
pytorch-lightning      0.7.3
pytz                   2020.1
PyYAML                 5.3.1
requests               2.22.0
requests-oauthlib      1.3.0
requests-unixsocket    0.2.0
resampy                0.2.2
rsa                    4.0
scikit-learn           0.23.1
scipy                  1.4.1
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
SoundFile              0.10.3.post1
ssh-import-id          5.10
systemd-python         234
tensorboard            2.2.2
tensorboard-plugin-wit 1.6.0.post3
test-tube              0.7.5
threadpoolctl          2.1.0
torch                  1.4.0
torchvision            0.5.0
tqdm                   4.46.1
Twisted                18.9.0
typing-extensions      3.7.4.2
ubuntu-advantage-tools 20.3
ufw                    0.36
unattended-upgrades    0.1
Unidecode              1.1.1
urllib3                1.25.8
wadllib                1.3.3
Werkzeug               1.0.1
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1
```

I am running the code on a GTX2080ti and have tried updating pytorch with different CUDA binaries but without luck.

**Comment by seungwonpark** [comment]
Sorry, but I won’t be able to help you with your environment settings. However, please feel free to discuss about it here.

In case of pytorch/pytorch-lightning not being able to identify your GPU device, perhaps using NVIDIA pytorch docker will be helpful for you.

**Comment by seungwonpark** [comment]
Closing the issue due to inactivity.
