### ISSUE TITLE
Make train: raise ValueError('value should be one of int, float, str, bool, or torch.Tensor')

### ISSUE THREAD

**Issue by ghost** [mindslab-ai/cotatron#8]
I make install:
pip install -r requirements 

Then run training and get:
```
Traceback (most recent call last):
  File "cotatron_trainer.py", line 75, in <module>
    main(args)
  File "cotatron_trainer.py", line 54, in main
    trainer.fit(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in fit
    self.single_gpu_train(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 470, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 748, in run_pretrain_routine
    self.logger.log_hyperparams(ref_model.hparams)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 18, in wrapped_fn
    fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/tensorboard.py", line 113, in log_hyperparams
    exp, ssi, sei = hparams(params, {})
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/tensorboard/summary.py", line 156, in hparams
    raise ValueError('value should be one of int, float, str, bool, or torch.Tensor')
ValueError: value should be one of int, float, str, bool, or torch.Tensor
```

Singe GPU or multi same error. 
tried update tensorboard no make difference.

**Comment by xxoospring** [comment]
Have you solved this problem?

**Comment by seungwonpark** [comment]
@paklau99988 What was the version of the TensorBoard for your case? Can you show your result of `pip freeze`?

**Comment by McTi** [comment]
I'm seeing the same issue. Here's the result of my pip freeze

```
absl-py==0.11.0
appdirs==1.4.4
asn1crypto==0.24.0
astor==0.8.1
audioread==2.1.9
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cryptography==2.1.4
cycler==0.10.0
dataclasses==0.8
decorator==5.0.7
filelock==3.0.12
future==0.18.2
gast==0.2.2
gdown==3.12.2
google-pasta==0.2.0
grpcio==1.34.0
h5py==2.10.0
idna==2.6
importlib-metadata==3.3.0
inflect==5.3.0
joblib==1.0.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.3.1
librosa==0.8.0
llvmlite==0.36.0
Markdown==3.3.3
matplotlib==3.3.4
numba==0.53.1
numpy==1.18.5
omegaconf==2.0.6
opt-einsum==3.3.0
packaging==20.9
Pillow==8.2.0
pooch==1.3.0
protobuf==3.14.0
pycparser==2.20
pycrypto==2.6.1
pygobject==3.26.1
pyparsing==2.4.7
PySocks==1.7.1
python-apt==1.6.5+ubuntu0.5
python-dateutil==2.8.1
pytorch-lightning==0.7.1
pyxdg==0.25
PyYAML==5.4.1
requests==2.25.1
resampy==0.2.2
scikit-learn==0.24.2
scipy==1.5.4
SecretStorage==2.3.1
six==1.11.0
SoundFile==0.10.3.post1
tensorboard==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
threadpoolctl==2.1.0
torch==1.4.0
tqdm==4.60.0
typing-extensions==3.7.4.3
Unidecode==1.2.0
urllib3==1.26.4
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.4.0

```
BTW same issue seen with Python 3.6.9, 3.7.10

However, bumping the pytorch-lightning version to 0.7.3 does appear to fix the issue. Is this a valid thing to do?
